[#ftl]
[#setting locale="en_US"]
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- NewPage -->
<html lang="de">
<head>
<!-- Generated by de.unkrig.doclet.javadoc on ${generationDate?datetime} -->
<title>All Classes</title>
<meta name="date" content="${generationDate?date?string["yyyy-MM-dd"]}">
<link rel="stylesheet" type="text/css" href="stylesheet.css" title="Style">
<script type="text/javascript" src="script.js"></script>
</head>
<body>
<h1 class="bar">All&nbsp;Classes</h1>
<div class="indexContainer">
<ul>
[#list allClassesAndInterfaces?sort_by("simpleName") as coi]
 [#if coi.doc.isInterface()]
<li><a href="${coi.href}" title="interface in ${coi.doc.containingPackage().name()}" target="classFrame"><span class="interfaceName">${coi.doc.name()}</span></a></li>
 [#else]
<li><a href="${coi.href}" title="class in ${coi.doc.containingPackage().name()}" target="classFrame">${coi.doc.name()}</a></li>
 [/#if]
[/#list]
</ul>
</div>
</body>
</html>
