[#ftl]
[#setting locale="en_US"]
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- NewPage -->
<html lang="de">
<head>
<!-- Generated by de.unkrig.doclet.javadoc on ${generationDate?datetime} -->
<title>${class.name}${(" (" + windowTitle + ")")!""}</title>
<meta name="date" content="${generationDate?date?string["yyyy-MM-dd"]}">
<link rel="stylesheet" type="text/css" href="${home}stylesheet.css" title="Style">
<script type="text/javascript" src="${home}script.js"></script>
</head>
<body>
<script type="text/javascript"><!--
    try {
        if (location.href.indexOf('is-external=true') == -1) {
            parent.document.title="${class.name}${(" (" + windowTitle + ")")!""}";
        }
    }
    catch(err) {
    }
//-->
var methods = {"i0":9,"i1":9,"i2":9,"i3":9,"i4":9,"i5":9,"i6":9,"i7":9};
var tabs = {65535:["t0","All Methods"],1:["t1","Static Methods"],8:["t4","Concrete Methods"]};
var altColor = "altColor";
var rowColor = "rowColor";
var tableTab = "tableTab";
var activeTableTab = "activeTableTab";
</script>
<noscript>
<div>JavaScript is disabled on your browser.</div>
</noscript>
[#if top??]
${top}
[/#if]
<!-- ========= START OF TOP NAVBAR ======= -->
<div class="topNav"><a name="navbar.top">
<!--   -->
</a>
<div class="skipNav"><a href="#skip.navbar.top" title="Skip navigation links">Skip navigation links</a></div>
<a name="navbar.top.firstrow">
<!--   -->
</a>
<ul class="navList" title="Navigation">
<li><a href="${home}overview-summary.html">Overview</a></li>
<li><a href="package-summary.html">Package</a></li>
<li class="navBarCell1Rev">Class</li>
<li><a href="package-tree.html">Tree</a></li>
<li><a href="${home}deprecated-list.html">Deprecated</a></li>
<li><a href="${home}index-all.html">Index</a></li>
<li><a href="${home}help-doc.html">Help</a></li>
</ul>
[#if header??]
<div class="aboutLanguage">${header}</div>
[/#if]
</div>
<div class="subNav">
<ul class="navList">
<li>Prev&nbsp;Class</li>
<li><a href="${home}de/unkrig/commons/lang/ExceptionUtil.html" title="class in ${class.doc.containingPackage().name()}"><span class="typeNameLink">Next&nbsp;Class</span></a></li>
</ul>
<ul class="navList">
<li><a href="${home}index.html?${class.href}" target="_top">Frames</a></li>
<li><a href="${class.name}.html" target="_top">No&nbsp;Frames</a></li>
</ul>
<ul class="navList" id="allclasses_navbar_top">
<li><a href="${home}allclasses-noframe.html">All&nbsp;Classes</a></li>
</ul>
<div>
<script type="text/javascript"><!--
  allClassesLink = document.getElementById("allclasses_navbar_top");
  if(window==top) {
    allClassesLink.style.display = "block";
  }
  else {
    allClassesLink.style.display = "none";
  }
  //-->
</script>
</div>
<div>
<ul class="subNavList">
<li>Summary:&nbsp;</li>
<li>Nested&nbsp;|&nbsp;</li>
<li>Field&nbsp;|&nbsp;</li>
<li>Constr&nbsp;|&nbsp;</li>
<li><a href="#method.summary">Method</a></li>
</ul>
<ul class="subNavList">
<li>Detail:&nbsp;</li>
<li>Field&nbsp;|&nbsp;</li>
<li>Constr&nbsp;|&nbsp;</li>
<li><a href="#method.detail">Method</a></li>
</ul>
</div>
<a name="skip.navbar.top">
<!--   -->
</a></div>
<!-- ========= END OF TOP NAVBAR ========= -->
<!-- ======== START OF CLASS DATA ======== -->
<div class="header">
<div class="subTitle">${class.doc.containingPackage().name()}</div>
<h2 title="Class ${class.name}" class="title">Class ${class.name}</h2>
</div>
<div class="contentContainer">
<ul class="inheritance">
<li>java.lang.Object</li>
<li>
<ul class="inheritance">
<li>${class.doc.qualifiedName()}</li>
</ul>
</li>
</ul>
<div class="description">
<ul class="blockList">
<li class="blockList">
<hr>
<br>
<pre>public final class <span class="typeNameLabel">${class.name}</span>
extends java.lang.Object</pre>
<div class="block">Various assertion-related utility methods.</div>
</li>
</ul>
</div>
<div class="summary">
<ul class="blockList">
[#if class.doc.methods()?size > 0]
<li class="blockList">
<!-- ========== METHOD SUMMARY =========== -->
<ul class="blockList">
<li class="blockList"><a name="method.summary">
<!--   -->
</a>
<h3>Method Summary</h3>
<table class="memberSummary" border="0" cellpadding="3" cellspacing="0" summary="Method Summary table, listing methods, and an explanation">
<caption><span id="t0" class="activeTableTab"><span>All Methods</span><span class="tabEnd">&nbsp;</span></span><span id="t1" class="tableTab"><span><a href="javascript:show(1);">Static Methods</a></span><span class="tabEnd">&nbsp;</span></span><span id="t4" class="tableTab"><span><a href="javascript:show(8);">Concrete Methods</a></span><span class="tabEnd">&nbsp;</span></span></caption>
<tr>
<th class="colFirst" scope="col">Modifier and Type</th>
<th class="colLast" scope="col">Method and Description</th>
</tr>
[#list class.methodsSorted as m]
<tr id="i${m_index}" class="${[ "altColor", "rowColor" ][m_index % 2]}">
<td class="colFirst"><code>[#rt]
${m.doc.isStatic()?string("static ", "")}[#rt]
 [#if m.doc.typeParameters()?size > 0]
  &lt;[#t]
  [#list m.doc.typeParameters() as tp]
   ${tp?string?html}${tp_has_next?string(", ", "")}[#t]
  [/#list]
  &gt;&nbsp;[#t]
 [/#if]
${m.doc.returnType().toString()?html}</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="${home}${m.href}">${m.name}</a></span>([#rt]
 [#list m.doc.parameters() as p]
${p.type()?html}&nbsp;${p.name()}[#t]
${p_has_next?string(",&nbsp;", "")}[#t]
 [/#list]
)</code>
<div class="block">${m.firstSentenceOfDescription}</div>
</td>
</tr>
[/#list]
</table>
[/#if]
[#list class.baseClassesAndInterfaces as bt]
<ul class="blockList">
<li class="blockList"><a name="methods.inherited.from.class.${bt.doc.qualifiedName()}">
<!--   -->
</a>
<h3>Methods inherited from class&nbsp;${bt.doc.qualifiedName()}</h3>
<code>[#rt]
 [#list bt.methodsSorted as m]
  ${m.name}${m_has_next?string(", ", "")}[#t]
 [/#list]
</code></li>
</ul>
[/#list]
</li>
</ul>
</li>
</ul>
</div>
<div class="details">
<ul class="blockList">
<li class="blockList">
<!-- ============ METHOD DETAIL ========== -->
<ul class="blockList">
<li class="blockList"><a name="method.detail">
<!--   -->
</a>
<h3>Method Detail</h3>
[#list class.methods as m]
 [#list m.fragments as f]
<a name="${f}">
<!--   -->
</a>[#rt]
 [/#list]

<ul class="blockList">
<li class="blockList">
<h4>${m.name}</h4>
<pre>[#rt]
${m.doc.modifiers()}&nbsp;[#rt]
 [#if m.doc.typeParameters()?size > 0]
  &lt;[#t]
  [#list m.doc.typeParameters() as tp]
   ${tp?string?html}${tp_has_next?string(", ", "")}[#t]
  [/#list]
  &gt;&nbsp;[#t]
 [/#if]
${m.doc.returnType().toString()?html}&nbsp;${m.name}([#rt]
 [#list m.doc.parameters() as p]
  [#list p.annotations() as a]
   @${a.annotationType().simpleTypeName()} [#t]
  [/#list]
${p.type()?html}&nbsp;${p.name()}[#t]
${p_has_next?string(",&nbsp;", "")}[#t]
 [/#list]
)</pre>
<div class="block">${m.description}</div>
<dl>
 [#if m.returnValueDescription??]
<dt><span class="returnLabel">Returns:</span></dt>
<dd>${m.returnValueDescription}</dd>
 [/#if]
 [#if m.throwsTags?size > 0]
<dt><span class="throwsLabel">Throws:</span></dt>
  [#list m.throwsTags as tt]
<dd><code>${tt.exceptionQualifiedName}</code>[#rt]
   [#if tt.exceptionComment??]
    [#lt] - ${tt.exceptionComment}[#rt]
   [/#if]
   [#lt]</dd>
  [/#list]
 [/#if]
</dl>
</li>
</ul>
[/#list]
</li>
</ul>
</li>
</ul>
</div>
</div>
<!-- ========= END OF CLASS DATA ========= -->
<!-- ======= START OF BOTTOM NAVBAR ====== -->
<div class="bottomNav"><a name="navbar.bottom">
<!--   -->
</a>
<div class="skipNav"><a href="#skip.navbar.bottom" title="Skip navigation links">Skip navigation links</a></div>
<a name="navbar.bottom.firstrow">
<!--   -->
</a>
<ul class="navList" title="Navigation">
<li><a href="${home}overview-summary.html">Overview</a></li>
<li><a href="package-summary.html">Package</a></li>
<li class="navBarCell1Rev">Class</li>
<li><a href="package-tree.html">Tree</a></li>
<li><a href="${home}deprecated-list.html">Deprecated</a></li>
<li><a href="${home}index-all.html">Index</a></li>
<li><a href="${home}help-doc.html">Help</a></li>
</ul>
[#if footer??]
<div class="aboutLanguage">${footer}</div>
[/#if]
</div>
<div class="subNav">
<ul class="navList">
<li>Prev&nbsp;Class</li>
<li><a href="${home}de/unkrig/commons/lang/ExceptionUtil.html" title="class in ${class.doc.containingPackage().name()}"><span class="typeNameLink">Next&nbsp;Class</span></a></li>
</ul>
<ul class="navList">
<li><a href="${home}index.html?${class.doc.qualifiedName()?replace(".", "/")}.html" target="_top">Frames</a></li>
<li><a href="${class.name}.html" target="_top">No&nbsp;Frames</a></li>
</ul>
<ul class="navList" id="allclasses_navbar_bottom">
<li><a href="${home}allclasses-noframe.html">All&nbsp;Classes</a></li>
</ul>
<div>
<script type="text/javascript"><!--
  allClassesLink = document.getElementById("allclasses_navbar_bottom");
  if(window==top) {
    allClassesLink.style.display = "block";
  }
  else {
    allClassesLink.style.display = "none";
  }
  //-->
</script>
</div>
<div>
<ul class="subNavList">
<li>Summary:&nbsp;</li>
<li>Nested&nbsp;|&nbsp;</li>
<li>Field&nbsp;|&nbsp;</li>
<li>Constr&nbsp;|&nbsp;</li>
<li><a href="#method.summary">Method</a></li>
</ul>
<ul class="subNavList">
<li>Detail:&nbsp;</li>
<li>Field&nbsp;|&nbsp;</li>
<li>Constr&nbsp;|&nbsp;</li>
<li><a href="#method.detail">Method</a></li>
</ul>
</div>
<a name="skip.navbar.bottom">
<!--   -->
</a></div>
<!-- ======== END OF BOTTOM NAVBAR ======= -->
</body>
</html>
