[#ftl]
[#setting locale="en_US"]
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- NewPage -->
<html lang="de">
<head>
<!-- Generated by de.unkrig.doclet.javadoc${noTimestamp???string("", " on " + generationDate?datetime)} -->
<title>${class.name}${(" (" + windowTitle + ")")!""}</title>
[#if !noTimestamp??]
<meta name="date" content="${generationDate?date?string["yyyy-MM-dd"]}">
[/#if]
<link rel="stylesheet" type="text/css" href="${home}stylesheet.css" title="Style">
<script type="text/javascript" src="${home}script.js"></script>
</head>
<body>
<script type="text/javascript"><!--
    try {
        if (location.href.indexOf('is-external=true') == -1) {
            parent.document.title="${class.name}${(" (" + windowTitle + ")")!""}";
        }
    }
    catch(err) {
    }
//-->
var methods = {[#rt]
[#list class.methodsSorted as m]
 "i${m_index}":9${m_has_next?string(",", "")}[#t]
[/#list]
[#lt]};
var tabs = {65535:["t0","All Methods"],1:["t1","Static Methods"],8:["t4","Concrete Methods"]};
var altColor = "altColor";
var rowColor = "rowColor";
var tableTab = "tableTab";
var activeTableTab = "activeTableTab";
</script>
<noscript>
<div>JavaScript is disabled on your browser.</div>
</noscript>
[#if top??]
${top}
[/#if]
<!-- ========= START OF TOP NAVBAR ======= -->
<div class="topNav"><a name="navbar.top">
<!--   -->
</a>
<div class="skipNav"><a href="#skip.navbar.top" title="Skip navigation links">Skip navigation links</a></div>
<a name="navbar.top.firstrow">
<!--   -->
</a>
<ul class="navList" title="Navigation">
<li><a href="${home}overview-summary.html">Overview</a></li>
<li><a href="package-summary.html">Package</a></li>
<li class="navBarCell1Rev">Class</li>
<li><a href="package-tree.html">Tree</a></li>
<li><a href="${home}deprecated-list.html">Deprecated</a></li>
<li><a href="${home}index-all.html">Index</a></li>
<li><a href="${home}help-doc.html">Help</a></li>
</ul>
[#if header??]
<div class="aboutLanguage">${header}</div>
[/#if]
</div>
<div class="subNav">
<ul class="navList">
[#if previousClass??]
<li><a href="${home}${previousClass.href}" title="${previousClass.title}"><span class="typeNameLink">Prev&nbsp;Class</span></a></li>
[#else]
<li>Prev&nbsp;Class</li>
[/#if]
[#if nextClass??]
<li><a href="${home}${nextClass.href}" title="${nextClass.title}"><span class="typeNameLink">Next&nbsp;Class</span></a></li>
[#else]
<li>Next&nbsp;Class</li>
[/#if]
</ul>
<ul class="navList">
<li><a href="${home}index.html?${class.href}" target="_top">Frames</a></li>
<li><a href="${class.name}.html" target="_top">No&nbsp;Frames</a></li>
</ul>
<ul class="navList" id="allclasses_navbar_top">
<li><a href="${home}allclasses-noframe.html">All&nbsp;Classes</a></li>
</ul>
<div>
<script type="text/javascript"><!--
  allClassesLink = document.getElementById("allclasses_navbar_top");
  if(window==top) {
    allClassesLink.style.display = "block";
  }
  else {
    allClassesLink.style.display = "none";
  }
  //-->
</script>
</div>
<div>
<ul class="subNavList">
<li>Summary:&nbsp;</li>
[#if class.doc.innerClasses()?size > 0]
<li><a href="#nested.class.summary">Nested</a>&nbsp;|&nbsp;</li>
[#else]
<li>Nested&nbsp;|&nbsp;</li>
[/#if]
[#if class.fields?size > 0]
<li><a href="#field.summary">Field</a>&nbsp;|&nbsp;</li>
[#else]
<li>Field&nbsp;|&nbsp;</li>
[/#if]
<li>Constr&nbsp;|&nbsp;</li>
<li><a href="#method.summary">Method</a></li>
</ul>
<ul class="subNavList">
<li>Detail:&nbsp;</li>
[#if class.fields?size > 0]
<li><a href="#field.detail">Field</a>&nbsp;|&nbsp;</li>
[#else]
<li>Field&nbsp;|&nbsp;</li>
[/#if]
<li>Constr&nbsp;|&nbsp;</li>
<li><a href="#method.detail">Method</a></li>
</ul>
</div>
<a name="skip.navbar.top">
<!--   -->
</a></div>
<!-- ========= END OF TOP NAVBAR ========= -->
<!-- ======== START OF CLASS DATA ======== -->
<div class="header">
<div class="subTitle">${class.doc.containingPackage().name()}</div>
<h2 title="${class.category?cap_first} ${class.name}" class="title">${class.category?cap_first} ${class.toString(class.doc)}${class.typeParameters?html}</h2>
</div>
<div class="contentContainer">


[#if class.superclassChain?size > 0]
 [#list class.superclassChain?reverse as sc]
<ul class="inheritance">
<li>${sc.qualifiedName}</li>
<li>
 [/#list]
<ul class="inheritance">
<li>${class.qualifiedName}</li>
</ul>
 [#list class.superclassChain as sc]
</li>
</ul>
 [/#list]
[/#if]


<div class="description">
<ul class="blockList">
<li class="blockList">


[#if class.doc.typeParamTags()?size > 0]
<dl>
<dt><span class="paramLabel">Type Parameters:</span></dt>
 [#list class.doc.typeParamTags() as tpt]
<dd><code>${tpt.parameterName()}</code> - ${tpt.parameterComment()}</dd>
 [/#list]
</dl>
[/#if]


[#if class.knownSubinterfaces?size > 0]
<dl>
<dt>All Known Subinterfaces:</dt>
 [#list class.knownSubinterfaces as si]
<dd><a href="${home}${si.href}" title="${si.title}">${si.simpleName}</a>${si.typeParameters?html}</dd>
 [/#list]
</dl>
[/#if]


<hr>
<br>
<pre>[#rt]
public [#rt]
${class.doc.isFinal()?string("final ", "")}[#rt]
${class.doc.isClass()?string("class ", "interface ")}[#rt]
<span class="typeNameLabel">${class.name}${class.typeParameters?html}</span>[#rt]
[#if class.superclass??]

extends ${class.superclass.qualifiedName}${class.superclass.typeArguments}[#rt]
[/#if]
</pre>
[#if class.description != ""]
<div class="block">${class.description}</div>
[/#if]
[#if class.seeTags?size > 0]
<dl>
<dt><span class="seeLabel">See Also:</span></dt>
<dd>[#rt]
 [#list class.seeTags as st]
  [#lt]<a href="${home}${st.reference.href}"[#rt]
  [#if st.reference.title??]
   [#lt] title="${st.reference.title?html}"[#rt]
  [/#if]
  [#lt]><code>${st.reference.toString(class.doc)?html}</code></a>${st.label}[#rt]
  [#if st_has_next]
   , [#lt]
  [/#if]
 [/#list]
</dd>
</dl>
[/#if]
</li>
</ul>
</div>
<div class="summary">
<ul class="blockList">
<li class="blockList">
[#if class.fields?size > 0]
<!-- =========== FIELD SUMMARY =========== -->
<ul class="blockList">
<li class="blockList"><a name="field.summary">
<!--   -->
</a>
<h3>Field Summary</h3>
<table class="memberSummary" border="0" cellpadding="3" cellspacing="0" summary="Field Summary table, listing fields, and an explanation">
<caption><span>Fields</span><span class="tabEnd">&nbsp;</span></caption>
<tr>
<th class="colFirst" scope="col">Modifier and Type</th>
<th class="colLast" scope="col">Field and Description</th>
</tr>
 [#list class.fields as f]
<tr class="${[ "altColor", "rowColor" ][f_index % 2]}">
<td class="colFirst"><code>${f.doc.isStatic()?string("static ", "")}${f.doc.type()}</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="${home}${f.href}">${f.name}</a></span></code>
<div class="block">${f.firstSentenceOfDescription}</div>
</td>
</tr>
 [/#list]
</table>
</li>
</ul>
[/#if]


[#if class.nestedClassesAndInterfaces?size > 0]
<!-- ======== NESTED CLASS SUMMARY ======== -->
<ul class="blockList">
<li class="blockList"><a name="nested.class.summary">
<!--   -->
</a>
<h3>Nested Class Summary</h3>
<table class="memberSummary" border="0" cellpadding="3" cellspacing="0" summary="Nested Class Summary table, listing nested classes, and an explanation">
<caption><span>Nested Classes</span><span class="tabEnd">&nbsp;</span></caption>
<tr>
<th class="colFirst" scope="col">Modifier and Type</th>
<th class="colLast" scope="col">Class and Description</th>
</tr>
 [#list class.nestedClassesAndInterfaces as ncoi]
<tr class="${[ "altColor", "rowColor" ][ncoi_index % 2]}">
<td class="colFirst"><code>static ${ncoi.category}&nbsp;</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="${home}${ncoi.href}" title="${ncoi.title}">${ncoi.simpleName}</a>[#rt]
  [#if ncoi.doc.typeParameters()?size > 0]
   [#lt]&lt;[#rt]
   [#list ncoi.doc.typeParameters() as ncoitp]
    [#lt]<a href="${home}${ncoi.href}" title="type parameter in ${ncoi.simpleName}">${ncoitp.simpleTypeName()}</a>[#rt]
    [#if ncoitp_has_next]
     [#lt],[#rt]
    [/#if]
   [/#list]
   [#lt]&gt;[#rt]
  [/#if]
</span></code>
<div class="block">${ncoi.firstSentenceOfDescription}</div>
</td>
</tr>
 [/#list]
</table>
</li>
</ul>
[/#if]


[#if class.doc.methods()?size > 0]
<!-- ========== METHOD SUMMARY =========== -->
<ul class="blockList">
<li class="blockList"><a name="method.summary">
<!--   -->
</a>
<h3>Method Summary</h3>
<table class="memberSummary" border="0" cellpadding="3" cellspacing="0" summary="Method Summary table, listing methods, and an explanation">
[#if class.doc.isClass()]
<caption><span id="t0" class="activeTableTab"><span>All Methods</span><span class="tabEnd">&nbsp;</span></span><span id="t1" class="tableTab"><span><a href="javascript:show(1);">Static Methods</a></span><span class="tabEnd">&nbsp;</span></span><span id="t4" class="tableTab"><span><a href="javascript:show(8);">Concrete Methods</a></span><span class="tabEnd">&nbsp;</span></span></caption>
[#else]
<caption><span id="t0" class="activeTableTab"><span>All Methods</span><span class="tabEnd">&nbsp;</span></span><span id="t2" class="tableTab"><span><a href="javascript:show(2);">Instance Methods</a></span><span class="tabEnd">&nbsp;</span></span><span id="t3" class="tableTab"><span><a href="javascript:show(4);">Abstract Methods</a></span><span class="tabEnd">&nbsp;</span></span></caption>
[/#if]
<tr>
<th class="colFirst" scope="col">Modifier and Type</th>
<th class="colLast" scope="col">Method and Description</th>
</tr>
 [#list class.methodsSorted as m]
  [#lt]<tr id="i${m_index}" class="${[ "altColor", "rowColor" ][m_index % 2]}">
  [#lt]<td class="colFirst"><code>[#rt]
  [#lt]${m.doc.isStatic()?string("static ", "")}[#rt]
  [#if m.doc.typeParameters()?size > 0]
   &lt;[#t]
   [#list m.doc.typeParameters() as tp]
    ${tp?string?html}${tp_has_next?string(",", "")}[#t]
   [/#list]
   &gt;[#t]
   [#if m.doc.typeParameters()[0]?string?length > 10 || m.doc.typeParameters()?size > 1]
    <br>[#t]
   [#else]
    &nbsp;[#t]
   [/#if]
  [/#if]
  [#lt]${m.doc.returnType().asTypeVariable()???string(m.doc.returnType().qualifiedTypeName()?html, m.doc.returnType()?html)}</code></td>
  [#lt]<td class="colLast"><code><span class="memberNameLink"><a href="${home}${m.href}">${m.name}</a></span>([#rt]
  [#list m.doc.parameters() as p]
   [#if p.type().asTypeVariable()??]
    [#lt]<a href="${home}${class.href}" title="type parameter in ${class.simpleName}">${p.type()}</a>[#rt]
   [#else]
    [#lt]BB${p.type()?html}[#rt]
   [/#if]
   [#lt]&nbsp;${p.name()}[#rt]
   [#if p_has_next]
    [#lt],
    [#lt]${""?left_pad(m.name?length)}[#rt]
   [/#if]
  [/#list]
  [#lt])</code>[#rt]
  [#if m.firstSentenceOfDescription == ""]
   [#lt]&nbsp;[#rt]
  [#else]

   [#lt]<div class="block">${m.firstSentenceOfDescription}</div>
  [/#if]
  [#lt]</td>
  [#lt]</tr>
 [/#list]
 [#lt]</table>
[/#if]
[#list class.baseClassesAndInterfaces as bt]
<ul class="blockList">
<li class="blockList"><a name="methods.inherited.from.class.${bt.doc.qualifiedName()}">
<!--   -->
</a>
<h3>Methods inherited from class&nbsp;${bt.doc.qualifiedName()}</h3>
<code>[#rt]
 [#list bt.methodsSorted as m]
  ${m.name}${m_has_next?string(", ", "")}[#t]
 [/#list]
</code></li>
</ul>
[/#list]
</li>
</ul>
</li>
</ul>
</div>
<div class="details">
<ul class="blockList">
<li class="blockList">
[#if class.fields?size > 0]
<!-- ============ FIELD DETAIL =========== -->
<ul class="blockList">
<li class="blockList"><a name="field.detail">
<!--   -->
</a>
<h3>Field Detail</h3>
 [#list class.fields as f]
<a name="${f.name}">
<!--   -->
</a>
<ul class="${f_has_next?string("blockList", "blockListLast")}">
<li class="blockList">
<h4>${f.name}</h4>
<pre>${f.doc.modifiers()}&nbsp;${f.doc.type()} ${f.name}</pre>
<div class="block">${f.description}</div>
<dl>
<dt><span class="seeLabel">See Also:</span></dt>
<dd>[#rt]
 [#list f.seeTags as st]
  [#lt]<a href="${home}${st.reference.href}"[#rt]
  [#if st.reference.title??]
   [#lt] title="${st.reference.title?html}"[#rt]
  [/#if]
  [#lt]><code>${st.reference.toString(class.doc)?html}</code></a>${st.label}[#rt]
   , [#lt]
 [/#list]
<a href="${home}constant-values.html#${class.doc.qualifiedName()}.${f.name}">Constant Field Values</a></dd>
</dl>
</li>
</ul>
 [/#list]
</li>
</ul>
[/#if]
<!-- ============ METHOD DETAIL ========== -->
<ul class="blockList">
<li class="blockList"><a name="method.detail">
<!--   -->
</a>
<h3>Method Detail</h3>
[#list class.methods as m]
 [#list m.fragments as f]
<a name="${f}">
<!--   -->
</a>[#rt]
 [/#list]

<ul class="${m_has_next?string("blockList", "blockListLast")}">
<li class="blockList">
<h4>${m.name}</h4>
[#assign indent = m.doc.modifiers()]
[#if m.doc.typeParameters()?size > 0]
 [#assign indent = indent + "<"]
 [#list m.doc.typeParameters() as tp]
  [#assign indent = indent + tp?string]
  [#if tp_has_next]
   [#assign indent = indent + ","]
  [/#if]
 [/#list]
 [#assign indent = indent + ">"]
[/#if]
[#assign indent = indent + m.doc.returnType().toString() + " " + m.name]
<pre>[#rt]
 [#list m.doc.annotations() as a]
@${a.annotationType().simpleTypeName()}
 [/#list]
 [#if !class.doc.isInterface()]
${m.doc.modifiers()}&nbsp;[#rt]
 [/#if]
 [#if m.doc.typeParameters()?size > 0]
  &lt;[#t]
  [#list m.doc.typeParameters() as tp]
   ${tp?string?html}${tp_has_next?string(",", "")}[#t]
  [/#list]
  &gt;&nbsp;[#t]
 [/#if]
 [#if m.doc.returnType().asTypeVariable()??]
  [#lt]<a href="${home}${class.href}" title="type parameter in ${class.simpleName}">${m.doc.returnType()}</a>[#rt]
 [#else]
  [#lt]${m.doc.returnType()}[#rt]
 [/#if]
 [#lt]&nbsp;${m.name}([#rt]
 [#list m.doc.parameters() as p]
  [#list p.annotations() as a]
   @${a.annotationType().simpleTypeName()}[#lt]
[#rt]${""?left_pad(indent?length + 2)}[#rt]
  [/#list]
  [#if p.type().asTypeVariable()??]
   [#lt]<a href="${home}${class.href}" title="type parameter in ${class.simpleName}">${p.type()}</a>[#rt]
  [#else]
   [#lt]${p.type()?html}[#rt]
  [/#if]
  [#lt]&nbsp;${p.name()}[#rt]
  [#if p_has_next]
   ,[#lt]
   [#lt]${""?left_pad(indent?length + 2)}[#rt]
  [/#if]
 [/#list]
)[#rt]
[#if m.doc.thrownExceptionTypes()?size > 0]
 [#list m.doc.thrownExceptionTypes() as tet]
  [#if tet_index == 0]

   [#lt]${""?left_pad(indent?length - 5)}throws ${tet?html}[#rt]
  [#else]
   [#lt],
   [#lt]${""?left_pad(indent?length + 2)}${tet?html}[#rt]
  [/#if]
 [/#list]
[/#if]
</pre>
 [#if m.description != ""]
<div class="block">${m.description}</div>
 [/#if]
 [#if m.paramTags?size > 0 || m.returnValueDescription?? || m.throwsTags?size > 0]
<dl>
  [#if m.paramTags?size > 0]
<dt><span class="paramLabel">Parameters:</span></dt>
   [#list m.paramTags as pt]
<dd><code>${pt.name}</code> - ${pt.parameterComment}</dd>
   [/#list]
  [/#if]
  [#if m.returnValueDescription??]
<dt><span class="returnLabel">Returns:</span></dt>
<dd>${m.returnValueDescription}</dd>
  [/#if]
  [#if m.throwsTags?size > 0]
<dt><span class="throwsLabel">Throws:</span></dt>
   [#list m.throwsTags as tt]
<dd><code>${tt.exceptionQualifiedName}</code>[#rt]
    [#if tt.exceptionComment?? && tt.exceptionComment?length > 0]
     [#lt] - ${tt.exceptionComment}[#rt]
    [/#if]
    [#lt]</dd>
   [/#list]
  [/#if]
</dl>
 [/#if]
</li>
</ul>
[/#list]
</li>
</ul>
</li>
</ul>
</div>
</div>
<!-- ========= END OF CLASS DATA ========= -->
<!-- ======= START OF BOTTOM NAVBAR ====== -->
<div class="bottomNav"><a name="navbar.bottom">
<!--   -->
</a>
<div class="skipNav"><a href="#skip.navbar.bottom" title="Skip navigation links">Skip navigation links</a></div>
<a name="navbar.bottom.firstrow">
<!--   -->
</a>
<ul class="navList" title="Navigation">
<li><a href="${home}overview-summary.html">Overview</a></li>
<li><a href="package-summary.html">Package</a></li>
<li class="navBarCell1Rev">Class</li>
<li><a href="package-tree.html">Tree</a></li>
<li><a href="${home}deprecated-list.html">Deprecated</a></li>
<li><a href="${home}index-all.html">Index</a></li>
<li><a href="${home}help-doc.html">Help</a></li>
</ul>
[#if footer??]
<div class="aboutLanguage">${footer}</div>
[/#if]
</div>
<div class="subNav">
<ul class="navList">
[#if previousClass??]
<li><a href="${home}${previousClass.href}" title="${previousClass.title}"><span class="typeNameLink">Prev&nbsp;Class</span></a></li>
[#else]
<li>Prev&nbsp;Class</li>
[/#if]
[#if nextClass??]
<li><a href="${home}${nextClass.href}" title="${nextClass.title}"><span class="typeNameLink">Next&nbsp;Class</span></a></li>
[#else]
<li>Next&nbsp;Class</li>
[/#if]
</ul>
<ul class="navList">
<li><a href="${home}index.html?${class.doc.qualifiedName()?replace(".", "/")}.html" target="_top">Frames</a></li>
<li><a href="${class.name}.html" target="_top">No&nbsp;Frames</a></li>
</ul>
<ul class="navList" id="allclasses_navbar_bottom">
<li><a href="${home}allclasses-noframe.html">All&nbsp;Classes</a></li>
</ul>
<div>
<script type="text/javascript"><!--
  allClassesLink = document.getElementById("allclasses_navbar_bottom");
  if(window==top) {
    allClassesLink.style.display = "block";
  }
  else {
    allClassesLink.style.display = "none";
  }
  //-->
</script>
</div>
<div>
<ul class="subNavList">
<li>Summary:&nbsp;</li>
[#if class.doc.innerClasses()?size > 0]
<li><a href="#nested.class.summary">Nested</a>&nbsp;|&nbsp;</li>
[#else]
<li>Nested&nbsp;|&nbsp;</li>
[/#if]
[#if class.fields?size == 0]
<li>Field&nbsp;|&nbsp;</li>
[#else]
<li><a href="#field.summary">Field</a>&nbsp;|&nbsp;</li>
[/#if]
<li>Constr&nbsp;|&nbsp;</li>
<li><a href="#method.summary">Method</a></li>
</ul>
<ul class="subNavList">
<li>Detail:&nbsp;</li>
[#if class.fields?size == 0]
<li>Field&nbsp;|&nbsp;</li>
[#else]
<li><a href="#field.detail">Field</a>&nbsp;|&nbsp;</li>
[/#if]
<li>Constr&nbsp;|&nbsp;</li>
<li><a href="#method.detail">Method</a></li>
</ul>
</div>
<a name="skip.navbar.bottom">
<!--   -->
</a></div>
<!-- ======== END OF BOTTOM NAVBAR ======= -->
<p class="legalCopy"><small>BOTTOM</small></p>
</body>
</html>
