[#ftl]
[#setting locale="en_US"]
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- NewPage -->
<html lang="de">
<head>
<!-- Generated by de.unkrig.doclet.javadoc on ${generationDate?datetime} -->
<title>${package.name}${windowTitle???string(" (" + windowTitle + ")", "")}</title>
<meta name="date" content="${generationDate?date?string["yyyy-MM-dd"]}">
<link rel="stylesheet" type="text/css" href="${home}stylesheet.css" title="Style">
<script type="text/javascript" src="${home}script.js"></script>
</head>
<body>
<h1 class="bar"><a href="${home}${package.name?replace(".", "/")}/package-summary.html" target="classFrame">${package.name}</a></h1>
<div class="indexContainer">
[#if package.interfaces?size > 0]
<h2 title="Interfaces">Interfaces</h2>
<ul title="Interfaces">
 [#list package.interfaces?sort_by("name") as i]
<li><a href="${i.name}.html" title="interface in ${package.name}" target="classFrame"><span class="interfaceName">${i.name}</span></a></li>
 [/#list]
</ul>
[/#if]
[#if package.classes?size > 0]
<h2 title="Classes">Classes</h2>
<ul title="Classes">
 [#list package.classes?sort_by("name") as c]
<li><a href="${c.name}.html" title="class in ${package.name}" target="classFrame">${c.name}</a></li>
 [/#list]
</ul>
[/#if]
</div>
</body>
</html>
